POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Algum serviço alem daqueles",
    "description": "topzeraaaa",
    "price": 2999,
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fdepositphotos.com%2Fbr%2Fphotos%2Fbrasil.html&psig=AOvVaw0cXrkEXe9MIAQK6FHDTEsw&ust=1730993058368000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCODTmqGCyIkDFQAAAAAdAAAAABAE"
}

###

GET http://localhost:3000/api/services

###

GET http://localhost:3000/api/services/672b9016cd25f479356bc688

###

DELETE http://localhost:3000/api/services/672b8b52aaa1278282c0f9f6

###

PUT http://localhost:3000/api/services/672b9016cd25f479356bc688
Content-Type: application/json

{
    "name": "ALGUM SERVIÇO 2.1",
    "description": "festa muito divertida",
    "price": 1500,
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fdepositphotos.com%2Fbr%2Fphotos%2Fbrasil.html&psig=AOvVaw0cXrkEXe9MIAQK6FHDTEsw&ust=1730993058368000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCODTmqGCyIkDFQAAAAAdAAAAABAE"
}

###

POST  http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Festinha de 18",
    "author": "Eduardo Lira",
    "description": "Uma festa para comemorar mais um ano de vida",
    "budget": 3000,
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fdepositphotos.com%2Fbr%2Fphotos%2Fbrasil.html&psig=AOvVaw0cXrkEXe9MIAQK6FHDTEsw&ust=1730993058368000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCODTmqGCyIkDFQAAAAAdAAAAABAE",
    "services": [
        {
            "name": "Algum serviço 1",
            "description": "topzeraaaa",
            "price": 3000,
            "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fdepositphotos.com%2Fbr%2Fphotos%2Fbrasil.html&psig=AOvVaw0cXrkEXe9MIAQK6FHDTEsw&ust=1730993058368000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCODTmqGCyIkDFQAAAAAdAAAAABAE"
        },
        {
            "name": "Algum serviço 2",
            "description": "perfeito",
            "price": 1600,
            "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fdepositphotos.com%2Fbr%2Fphotos%2Fbrasil.html&psig=AOvVaw0cXrkEXe9MIAQK6FHDTEsw&ust=1730993058368000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCODTmqGCyIkDFQAAAAAdAAAAABAE"
        }
    ]
}

###

GET http://localhost:3000/api/parties

###

GET http://localhost:3000/api/parties/672c1fffc3ef94ff86bf1858

###

DELETE http://localhost:3000/api/parties/672c1fffc3ef94ff86bf1858